
services:
  - type: web
    name: planning-scraper
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/main.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
